name: Build and Publish GeoData
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3,15 * * *"  # Запуск в 3:30 и 15:30 UTC ежедневно
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=geodata" >> $GITHUB_ENV
          echo "TAG_NAME=geodata" >> $GITHUB_ENV
          
          echo "GEOIP_URL=https://raw.githubusercontent.com/ristavor/geoip/release/geoip.dat" >> $GITHUB_ENV
          echo "GEOSITE_URL=https://raw.githubusercontent.com/ristavor/geosite/release/geosite.dat" >> $GITHUB_ENV
        shell: bash

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/geodat2srs
          path: geodat2srs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geodat2srs/go.mod

      - name: Collect files
        run: |
          mkdir -p ./publish
          # Скачиваем только необходимые файлы без .sha256sum
          curl -sSL $GEOIP_URL > ./publish/geoip.dat
          curl -sSL $GEOSITE_URL > ./publish/geosite.dat
        shell: bash

      - name: Generate sing-box srs
        run: |
          go build -C geodat2srs ./
          ./geodat2srs/geodat2srs geoip -i ./publish/geoip.dat -o ./tmp/sing-box/rule-set-geoip/
          ./geodat2srs/geodat2srs geosite -i ./publish/geosite.dat -o ./tmp/sing-box/rule-set-geosite/
          cd ./tmp/sing-box || exit 1
          zip -r ../../publish/sing-box.zip *
        shell: bash

      - name: Remove sing-box.zip before uploading
        run: |
          rm -f ./publish/sing-box.zip
        shell: bash

      - name: Upload files to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          files: |
            ./publish/geoip.dat
            ./publish/geosite.dat
            ./publish/sing-box.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Шаг "Git push assets to 'release' branch" удалён, так как управление ассетами осуществляется через GitHub Releases

      # Шаг "Purge jsdelivr CDN" удалён, так как он не требуется при использовании GitHub Releases
